/*
The skill list below is just an example. In reality it should grab all the skills from the DB table which stores our skills.
The job description text is also just an example. In reality it should grab the text from the job dialog window.
*/

let skills = ['Abgeschlossene Berufsausbildung',
 'Bachelor',
 'ETH',
 'FH',
 'Führerausweis',
 'HF',
 'Informatiklehre EFZ',
 'IPMA',
 'Kaufm. Grundausbildung / Lehre',
 'Master',
 'Matura',
 'MS-Zertifikate',
 'Mediamatiker EFZ',
 ' ISS',
 ' PMP',
 ' PRINCE',
 ' SAQ',
 ' Technikerschule',
 ' Telematikerlehre',
 ' Universität',
 'Webpublisher',
 'CAD',
 'Webdesign',
 'Adobe CS',
 'MS-Office',
 'Navision',
 'Eclipse',
 'Hibernate',
 'Hybris',
 'Jbuilder',
 'Powerdesigner',
 'RUP',
 'SCRUM',
 'Salesforce',
 'SOA',
 'Synon',
 'Visual Studio',
 'Apache',
 'Avaloq',
 'Bloomberg',
 'EBS',
 'EUREX',
 'Finnova',
 'Opentext',
 'POS (Point of Sale',
 'Reuters',
 'TIVOLI',
 'TSO',
 'Typo3',
 'XAL',
 'XETRA',
 'Mandarin',
 'Deutsch',
 'Englisch',
 'Französisch',
 'Rumantsch',
 'Niederländisch',
 'Italienisch',
 'Kantonesisch',
 'Japanisch',
 'Portugiesisch',
 'Russisch',
 'Spanisch',
 'XSLT',
 'Access',
 'dBASE',
 'mSQL',
 'MySQL',
 'Tamino',
 'PostgreSQL',
 'Adabas',
 'FastObjects',
 'Caché',
 'Sybase',
 'SQL Server',
 'Informix',
 'InterBase',
 'DB2',
 'Oracle',
 'Android',
 'iOS',
 'Linux',
 'LynxOS',
 'Mac OS',
 'MS-DOSNOVELL',
 'OS2',
 'OS2200',
 'OS390',
 'OS400',
 'Sharepoint',
 'Solaris',
 'UNIX',
 'Vista',
 'W2003',
 'W2008',
 'W2012',
 'W2016',
 'W2019',
 'Windows 7',
 'Windows 8',
 'Windows 10',
 'Microsoft Azure',
 'Windows 11',
 'z/OS',
 'Elektronik allgemein',
 'Hardware allgemein',
 'Mikrosystem',
 'Chemie',
 'Mathematik',
 'Patentwesen',
 'Physik',
 'Psychologie',
 'Automobil',
 'Bauwesen',
 'Biochemie',
 'Biologie',
 'Einzel-/Detailhandel',
 'Energiewirtschaft',
 'Fotographie',
 'Grafische Erzeugnisse / Verlage',
 'Grosshandel',
 'Immobilien',
 'Industrie',
 'IT-Dienstleister',
 'Krankenkasse',
 'Logistik',
 'Maschinen / Apparate / Instrumente',
 'Medien',
 'Gesundheitswesen',
 'Musik',
 'Pharma /Chemie',
 'Retail',
 'Sozialer Bereich',
 'Telekommunikation',
 'Textilindustrie',
 'Tourismus/Reisen/Gastronomie',
 'Transport / Verkehr / Nachrichten',
 'Treuhand',
 'Uebrige Dienstleistungen',
 'Versicherung',
 'Verwaltung',
 'Account Management',
 'Sales',
 'Auditing',
 'Betriebswirtschaft',
 'Black Belt',
 'Branding',
 'Business Intelligence',
 'Business Objects',
 'Business Process Engineering',
 'CMS',
 'Coaching',
 'Compliance',
 'CRM',
 'Cross Media',
 'Certified Scrum Master',
 'Datawarehouse',
 'Dokumentenmanagement',
 'EAI',
 'Ebanking',
 'ECM (Enterprise Content Managment',
 'E-commerce',
 'Hardwarebeschaffung',
 'E-Learning',
 'ERP',
 'ETL',
 'Geoinformatik',
 'ISO',
 'ITIL',
 'JDEdwards',
 'Junior',
 'Kommunikationsspezialist',
 'Konzeptionell / Analytisch',
 'Kryptografie / Verschlüsselung',
 'Management / Führung',
 'Marketing',
 'Masterdata',
 'Medizinische Anwendungen',
 'MIS',
 'OO-Design / Analyse',
 'Outputmanagement',
 'Outsourcing',
 'Projektleitung',
 'Qualitätssicherung',
 'Reisetaetigkeit',
 'Requirements Engineering',
 'Risk Management',
 'SAP',
 'Schulung',
 'Security',
 'Senior',
 'SEO',
 'SLA',
 'Social Media',
 'Softwarearchitektur',
 'Storagemanagement',
 'Strategie',
 'Support',
 'Systemarchitektur',
 'Test',
 'Usability',
 'Google Analytics',
 'Call Center',
 'Citrix',
 'CLOUD',
 'Hyper-V',
 'SCCM/MECM',
 'Softwareverteilung',
 'Terminalserver',
 'Ticketing',
 'Virtualisierung',
 'VMware',
 'XENZEN',
 'Buchhaltung',
 'Galileo',
 'Human Resources',
 'Kundenbetreuung',
 'Revision',
 'Telefon',
 'Wertschriften',
 'Control M',
 'Pikett',
 'SAP Administration / Technische Seite',
 'Schicht',
 'Sysplex',
 'Aspect Telefonswitch',
 'Avaya',
 'Billing',
 'Broadcast',
 'Cisco',
 'Directory-Services',
 'DWDM',
 'Ethernet',
 'Firewall',
 'HP Openview',
 'IPTV',
 'LAN',
 'MS Teams',
 'MGCP',
 'Mobile',
 'Monitoring',
 'MPLS',
 'NAS',
 'Network Node Manager (HP Openview',
 'Netzwerkarchitekturen',
 'Netzwerkmanagement',
 'Nortel',
 'SAN',
 'SDH',
 'SNMP',
 'Streaming-Media',
 'TCP/IP',
 'Telefonie',
 'Video',
 'Voice over IP',
 'VoIP Gateaway',
 'VPN',
 'WAN',
 'Webkommunikation',
 'Wimax',
 'Wireless',
 'Python',
 'Perl',
 'Visual Basic .NET',
 'Ruby',
 'Visual Basic',
 'Assembly language',
 'Delphi/Object Pascal',
 'Swift',
 'Objective-C',
 'Machine Learning',
 'MATLAB',
 'PL/SQL',
 'D',
 'COBOL',
 'Fortran',
 'Scratch',
 'ABAP',
 'Dart',
 'SAS',
 'Groovy',
 'Transact-SQL',
 'Lisp',
 'Ada',
 'Scala',
 'Lua',
 'Logo',
 'Prolog',
 'Scheme',
 'RPG (OS/400',
 'LabVIEW',
 'OpenEdge ABL',
 'Erlang',
 'Haskell',
 'Alice',
 'Apex',
 'Bash',
 'F#',
 'Q',
 'Ladder Logic',
 'Rust',
 'Awk',
 'Go',
 '(Visual FoxPro',
 'VBScript',
 '.NET',
 'ABACUS',
 'ABAP',
 'Vue.js',
 'React',
 'AJAX',
 'Kotlin',
 'ASP.NET',
 'Angular',
 'Assembler',
 'Asterisk',
 'AXAPTA',
 'C',
 'C#',
 'C++',
 'Centura',
 'CGI',
 'CL (Comand Language',
 'ClearCase',
 'Clipper',
 'CNC',
 'Cobol',
 'Cognos',
 'ColdFusion',
 'CORBA',
 'Crystal Report',
 'CSS3',
 'Dbase',
 'DCOM',
 'DELPHI',
 'DHTML',
 'Embedded SW',
 'Filemaker',
 'FileNET',
 'Flash',
 'Fortran',
 'FoxPro',
 'GUI',
 'HTML5',
 'Hyperion',
 'J2EE',
 'J2SE',
 'JAVA',
 'JavaScript',
 'jbase',
 'JCL',
 'jQuery',
 'JSP',
 'JSF',
 'Kanban',
 'LabVIEW',
 'Lotus Script',
 'Matlab',
 'MFC',
 'Middleware',
 'Modula',
 'Motif',
 'MQ Series',
 'Oracle-Designer',
 'Pascal',
 'PERL',
 'PHOENIX',
 'PHP',
 'PL1',
 'PLSQL',
 'Powershell',
 'Powerbuilder',
 'Powerflex',
 'PROFIBUS',
 'Prolog',
 'Python',
 'Qt',
 'R',
 'REXX',
 'RPG',
 'Ruby',
 'SAP Web Application Server',
 'SAS',
 'Shell-Scripts',
 'Siebel',
 'Silverlight',
 'SIMATIC',
 'SMALL TALK',
 'SPS',
 'SPSS',
 'SQL',
 'SSG',
 'Swing',
 'Synon',
 'TCL',
 'TSQL',
 'Tuxedo',
 'UML',
 'Uniface',
 'V+',
 'VBA',
 'VBS',
 'VHDL',
 'Vignette',
 'VisiWeb',
 'Visual Age',
 'VISUAL BASIC',
 'Weblogic',
 'WebObjects',
 'Websphere',
 'WIN CC',
 'WML – Script',
 'X++',
 'XHTML',
 'XML',
 'XSL',
 'XSLT',
 'CCT',
 'CCNA',
 'CCDA',
 'CCNP',
 'CCDP',
 'CCIP',
 'CCDE',
 'CCIE',
 'CCA',
 'CICS',
 'IBM DB2 Information Management',
 'IBM WebSphere',
 'IBM WebSphere Business Integration',
 'Linux',
 'IBM Notes',
 'Tivoli Software',
 'XML',
 'AIX and IBM pSeries',
 'IBM iSeries',
 'IBM xSeries (Netfinity',
 'IBM System z (s/390',
 'IBM TotalStorage',
 'Foundation Level: Certified Professional for Requirements Engineering (CPRE-FL',
 'CPRE AL Requirements Elicitation and Consolidation',
 'CPRE AL Requirements Modeling',
 'Foundation Level: Certified Professional for Software Architecture (CPSA-F',
 'Advanced Level (CPSA-A',
 'Expert Level (CPSA-E',
 ' in Vorbereitung beim iSAQB',
 'ITIL Foundation',
 'ITIL Intermediate',
 'ITIL Expert',
 'LPIC-1 – Junior Level Linux Professional',
 'LPIC-2 – Advanced Level Linux Professional',
 'LPIC-3 – Senior Level Linux Professional',
 'RHCSA - Red Hat Certified System Administrator',
 'RHCE – Red Hat Certified Engineer',
 'RHCVA - Red Hat Certified Virtualization Administrator',
 'RHCSS – Red Hat Certified Security Specialist',
 'RHCDS – Red Hat Certified Datacenter Specialist',
 'RHCA – Red Hat Certified Architect',
 'Novell Certified Linux Administrator',
 'Novell Certified Linux Desktop Administrator',
 'Novell Certified Linux Professional',
 'Novell Certified Linux Engineer',
 'MCP',
 'MCP+I',
 'MCAD',
 'MCAS',
 'MCDBA',
 'MCSA',
 'MCSD',
 'MCSE',
 'MCT',
 'MSS',
 'MCTS',
 'MCITP',
 'MCPD',
 'MOS',
 'MCAS',
 'MCAP',
 'MCM',
 'MCSM',
 'MCA',
 'MTA',
 'mySap',
 'SAP BI',
 'SAP BO',
 'SAP BW',
 'SAP CO',
 'SAP CRM',
 'SAP CS',
 'SAP ERP',
 'SAP FI',
 'SAP HANA',
 'SAP HR',
 'SAP LO',
 'SAP MDM',
 'SAP MM',
 'SAP PLM',
 'SAP PM',
 'SAP PP',
 'SAP PS',
 'SAP QM',
 'SAP Retail',
 'SAP SD',
 'SAP SRM',
 'SAP TM',
 'SAP TR',
 'SAP WM',
 'ACE - Adobe Certified Expert',
 'MCAP – Microsoft Certified Application Professional',
 'MOS - Microsoft Office Specialis',
 'SIZ - Schweizerisches Informatik-Zertifikat',
 'Agile Project Management Certification (AgilePM',
 'ISO/IEC 20000 Certification',
 'ISO/IEC 27001 Certification',
 'OBASHI Certification',
 'Service Level Analyst Certification',
 'Service Catalogue Certification',
 'Problem Analyst Certification',
 'ACDT – Apple Certified Desktop Technician',
 'ACP – Apple Certified Pro',
 'ACPT – Apple Certified Portable Technician',
 'ACSA – Apple Certified System Administrator',
 'ACSE – Apple Certified Service Engineer',
 'ACSP – Apple Certified Support Professional',
 'APP - Apple Product Professional',
 'CompTIA A+',
 'CompTIA Network+',
 'CompTIA Server+',
 'CompTIA Security+',
 'CompTIA CTT+',
 'CompTIA Project+',
 'CompTIA PDI+',
 'CompTIA Linux+',
 'CompTIA Healthcare IT Techniciann',
 'CompTIA Cloud+',
 'CompTIA CDIA+',
 'CompTIA Convergence+',
 'CompTIA Advanced Security Practitioner',
 'Hermes',
 'Scrum',
 'CSQE',
 'CSQA',
 'CSTE',
 'ISTQB',
 'CCSP – Citrix Certified Sales Professional',
 'Certified Associate (ersetzt CCA',
 'Certified Professional (ersetzt CCEE',
 'Certified Expert (ersetzt CCIA',
 'CCI – Citrix Certified Instructor',
 'IBM Domino Server',
 'NoSQL',
 'Active Directory',
 'Exchange',
 'Banken / Finanzgesellschaften',
 'KIS (Klinikinformations-/Krankenhausinformationssystem',
 'IAM (Identity and Access Management',
 'Bootstrap',
 'JSON',
 'Node.js',
 'UCC (Unified Communications & Collaborations',
 'UX (User Experience',
 'Spring',
 'DevOps',
 'Wirtschaftsinformatik',
 'Business Analyse',
 'Wordpress',
 'Jira',
 'CISSP',
 'CISM',
 'Bioinformatik',
 'Test-driven development (TDD',
 'Dynamics 365',
 'Informatiker EFZ',
 'Bachelor',
 'Master',
 'CAS',
 'DAS',
 'MAS',
 'Mediamatiker EFZ',
 'RPA'];

 let skillsUppercased = skills.map(skill => skill.toUpperCase());
 
 console.log(skillsUppercased);

let text = 'Aufgaben: First Level deutsch (gesamter Workplace) und Second Level (Clients) Support Automatisiertes Aufsetzen und Betreiben von Windowssystemen Automatisieren von Softwareinstallationen Mitarbeit in ICT Projekten Mitwirkung bei der Ausbildung der Lernenden und den ICT-Einführungen für Mitarbeitende und Studierende Ihr Profil: Fundierte Ausbildung in Informatik (z.B. EFZ) und/oder entsprechende Berufserfahrung Von Vorteil sind fundierte Kenntnisse in den Bereichen Windows Clients, VDI (VMware Horizon), Active Directory und in der Automatisierung/Scripting mit PowerShell Fachlich vielseitiges Interesse und Bereitschaft, sich gerne mit modernsten ICT-Technologien auseinanderzusetzen Fähigkeit zur zielgruppengerechten Kommunikation Bereitschaft zur laufenden fachlichen Weiterentwicklung Selbständige Arbeitsweise im Team, Belastbarkeit';

let textFormatted = text.replaceAll(",", "").replaceAll(":", "").replaceAll(".", "").replaceAll(";", "").replaceAll("(", "").replaceAll(")", "").toUpperCase().split(' ');

console.log(textFormatted);

let duplicates = textFormatted.filter(function(val) {
    return skillsUppercased.indexOf(val) != -1;
});

console.log(duplicates);

/*
The part of the code which sets the duplicates into a new array of skills belonging to this specific job is not in here because I wasn't sure how to write it.
*/
